### ISSUE TITLE
Node-Sass Error

### ISSUE THREAD

**Issue by D3v3l0per1** [cschweda/jekyll-vue-boilerplate#2]
I always get this error when i install the dependencies :c Maybe someone know why? Its a fresh installation.

```
/2] ⠂ waiting...
error C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@10.16.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MW\\Desktop\\Webstuff\\jekyll-vue-boilerplate\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\MW\Desktop\Webstuff\jekyll-vue-boilerplate\node_modules\node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
```

**Comment by cschweda** [comment]
Looks like this might be one cause:

```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
```
